#!/bin/sh

alias zsh-update-plugins="find "$ZDOTDIR/plugins" -type d -exec test -e '{}/.git' ';' -print0 | xargs -I {} -0 git -C {} pull -q"
[ -x `command -v lsd` ] && alias ls="lsd"
[ -x `command -v bat` ] && alias cat="bat"
