#!/usr/bin/env bash

HISTFILE="$ZDOTDIR"/.zsh_history
HISTSIZE=1000000
SAVEHIST=1000000

export MANWIDTH=999
export PATH="$HOME/.local/bin":$PATH

export EDITOR="micro"
export PAGE="bat"
export VISUAL="micro"

export STARSHIP_CONFIG="$XDG_CONFIG_HOME"/starship/starship.toml
